[package]
name = "dp-crypto"
version = "0.1.0"
edition = "2024"

[dependencies]
ark-bn254 = { version = "0.5.0", features = ["std"]}
ark-std = { version = "0.5.0", features = ["std","getrandom"]}
ark-ec = { version = "0.5.0", features = ["std"]}
ark-ff = { version = "0.5.0", features = ["std"] }
ark-poly = { version = "0.5.0", features = ["std"]}
anyhow = "1.0.100"
blake3 = "1.8.2"
tracing = "0.1.41"
rayon = "1.11.0"
ark-serialize = { version = "0.5.0", features = ["derive"] }
ark-poly-commit = "0.5.0"
rand_chacha = "0.3.1"
serde = { version = "1.0.228", features = ["derive"] }

[features]
default = ["mono"]
parallel = [
    "ark-ec/parallel",
    "ark-ff/parallel",
    "ark-poly/parallel",
    "ark-std/parallel",
]
mono = []

[dev-dependencies]
serde_json = "1.0.145"
